### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ZekeSmith** [PolyMC/polymc.github.io#16]
This is a todo list for features that need to be addressed or changed
- [x] New about page [#15]
- [x] New Download Page
- [x] Finish wiki css
- [ ] Alert tags for news

**Comment by dada513** [comment]
Maybe download page should have links to separate pages for different os/distro?

Or we can also make a drop down to choose distro. Pretty sure can be done with weird html tags instead of JS
